#!/usr/bin/env php
<?php
// +----------------------------------------------------------------------
// | ThinkPHP [ WE CAN DO IT JUST THINK ]
// +----------------------------------------------------------------------
// | Copyright (c) 2006-2018 http://thinkphp.cn All rights reserved.
// +----------------------------------------------------------------------
// | Licensed ( http://www.apache.org/licenses/LICENSE-2.0 )
// +----------------------------------------------------------------------
// | Author: yunwuxin <448901948@qq.com>
// +----------------------------------------------------------------------

namespace think;

// 加载基础文件
require __DIR__ . '/vendor/thinkphp/base.php';
define('CMF_ROOT', __DIR__ . '/');
define('CMF_DATA', CMF_ROOT . 'data/');
define('APP_DEBUG', 1);
define('WEB_ROOT', __DIR__ . '/public');
// 定义应用目录
define('APP_PATH', CMF_ROOT . 'app/');
//require __DIR__ . '/PhalApi/Common/functions.php';

// 应用初始化
Container::get('app')->path(__DIR__ . '/app/')->initialize();

// 控制台初始化
Console::init();